name: hello-world
on:
  push:
  delete:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  delete_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "File deleted!"
